print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
tip = float(input("What percentage tip would you like to give? 10, 12 or 15? "))
people = float(input("How many people to split the bill? "))
per_person = round((bill / people) * (1 + tip / 100), 2)
print(f"Each person should pay: ${per_person}")
