question_data = [
        {
            "category": "Animals",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Ceratosaurus, a dinosaur known for having a horn on the top of its nose, is also known to be a decendent of the Tyrannosaurus Rex.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Greenland is almost as big as Africa.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The bikini is named after the &quot;Bikini Atoll&quot;, an island where the United States conducted tests on atomic bombs.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "easy",
            "question": "Bulls are attracted to the color red.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Mythology",
            "type": "boolean",
            "difficulty": "easy",
            "question": "According to Greek Mythology, Zeus can control lightning.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "hard",
            "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "Geography",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The Sonoran Desert is located in eastern Africa.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "category": "Entertainment: Video Games",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The character that would eventually become Dr. Eggman was considered for the role of Sega&#039;s new flagship mascot before Sonic was.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "category": "General Knowledge",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Popcorn was invented in 1871 by Frederick W. Rueckheim in the USA where he sold the snack on the streets of Chicago.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ]

